name: Update Files and Deploy

on:
  schedule:
    - cron: '0 0 * * *' # Runs every 5 minutes

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Files
        run: |
          echo "Update 1: $(date)" > googleanalytics.R
          echo "Update 2: $(date)" > index.Rmd

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add googleanalytics.R index.Rmd
          git commit -m "Update files ($(date +'%Y-%m-%d %H:%M:%S'))"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Change this to the directory where your static files are located