on:
  schedule:
    - cron: '25 12 * * *' # Runs every 5 minutes
  push:
    branches: main
permissions:
  contents: write

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googleAnalyticsR

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("googleanalytics.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.Rmd
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"e directory where your static files are located
