on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-report:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::rmarkdown
            any::knitr
            any::remotes
            any::slickR
            any::gsheet

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("index.Rmd", "html_document")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          target: gh-pages 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./